import os
from supabase import create_client, Client
from dotenv import load_dotenv
import logging

load_dotenv(".env.local", override=True)

class SupabaseSync:
    def __init__(self):
        url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
        key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") # Use service role for backend sync
        if not url or not key:
            logging.error("Supabase credentials missing in Backend/.env.local")
            self.client = None
        else:
            self.client = create_client(url, key)

    def sync_story(self, story_id, story_data):
        """Sync a processed story from Python Memory to Supabase News Articles table"""
        if not self.client: return

        try:
            # Map Python Story structure to Supabase news_articles table
            payload = {
                "id": story_id,
                "title": story_data.get("main_topic", "Unknown"),
                "content": story_data.get("subreport", ""), # Use subreport as content depth
                "source": "AI_INFERENCE_ENGINE",
                "published_at": story_data.get("created_at", ""),
                "processed": True,
                "sentiment_score": story_data.get("current_hypothesis", {}).get("sentiment_score", 0),
                "entities": story_data.get("entities", [])
            }

            self.client.table("news_articles").upsert(payload, on_conflict="id").execute()
            logging.info(f"Supabase Sync: Story {story_id} synchronized.")
        except Exception as e:
            logging.error(f"Supabase Sync Failure (Story): {e}")

    def sync_signal(self, user_id, story_id, signal_data):
        """Sync an AI Signal generated by the decision engine"""
        if not self.client: return

        try:
            payload = {
                "user_id": user_id,
                "story_id": story_id,
                "symbol": signal_data.get("ticker", "UNKNOWN"),
                "signal_type": signal_data.get("signal", "HOLD"),
                "confidence": signal_data.get("confidence", 0.5),
                "reasoning": signal_data.get("reasoning", ""),
                "reasoning_layers": signal_data.get("reasoning_layers", {})
            }

            self.client.table("signals").insert(payload).execute()
            logging.info(f"Supabase Sync: Signal for {payload['symbol']} synchronized.")
        except Exception as e:
            logging.error(f"Supabase Sync Failure (Signal): {e}")

# Global instance
sync_engine = SupabaseSync()
